config/routes.rb
LiamJqueryAjaxSample::Application.routes.draw do
  resources :tasks

  root :to => 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :complete, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @incomplete_tasks = Task.where(complete: !true)
    @completed_tasks = Task.where(complete: true)
  end

  def new
    @task = Task.new
  end
  
  def create
    @task = Task.new(params[:task])
    @task.complete = false
    @task.save!
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.js
    end
  end
  
  def update
    @task = Task.find(params[:id])
    @task.update_attributes!(params[:task])
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.js
    end
  end
  
  def destroy
    @task = Task.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LiamJqueryAjaxSample</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task, remote: true do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/tasks/_task.html.erb
<%= form_for task, remote: true do |f| %>
  <%= f.check_box :complete %>
  <%= f.submit "Update" %>
  <%= f.label :complete, task.name %>
  <%= link_to "(remove)", task, method: :delete, remote: true, data: { confirm: "Are you sure" } %>
<% end %>

app/views/tasks/create.js.erb
$('#new_task').remove();
$('#new_link').show();
$('#incomplete_tasks').append('<%= j render(@task) %>');
$('#edit_task_<%= @task.id %>').submitOnCheck();

app/views/tasks/destroy.js.erb
$('#edit_task_<%= @task.id %>').remove();

app/views/tasks/index.html.erb
<h1>Check Lists</h1>

<%= link_to "New Task", new_task_path, id: "new_link", remote: true %>

<h2>Incomplete Tasks</h2>
<div class="tasks" id="incomplete_tasks">
  <%= render @incomplete_tasks %>
</div>

<h2>Complete Tasks</h2>
<div class="tasks" id="complete_tasks">
  <%= render @completed_tasks %>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<p><%= link_to "Back to tasks", tasks_path %>

app/views/tasks/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>')

app/views/tasks/update.js.erb
<% if @task.complete? %>
	$('#edit_task_<%= @task.id %>').appendTo('#complete_tasks');
<% else %>
	$('#edit_task_<%= @task.id %>').appendTo('#incomplete_tasks');
<% end %>